# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Author

# Model Form Field configuration
form: $/fmateo/library/models/author/fields.yaml

# Model Class name
modelClass: Fmateo\Library\Models\Author

# Default redirect location
defaultRedirect: fmateo/library/author

# Create page
create:
    title: Create Author
    redirect: fmateo/library/author/update/:id
    redirectClose: fmateo/library/author

# Update page
update:
    title: Edit Author
    redirect: fmateo/library/author
    redirectClose: fmateo/library/author

# Preview page
preview:
    title: Preview Author
