# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Book

# Model Form Field configuration
form: $/fmateo/library/models/book/fields.yaml

# Model Class name
modelClass: Fmateo\Library\Models\Book

# Default redirect location
defaultRedirect: fmateo/library/book

# Create page
create:
    title: Create Book
    redirect: fmateo/library/book/update/:id
    redirectClose: fmateo/library/book

# Update page
update:
    title: Edit Book
    redirect: fmateo/library/book
    redirectClose: fmateo/library/book

# Preview page
preview:
    title: Preview Book
